apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-component-e2e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-component-e2e
    app.kubernetes.io/part-of: e2e-demo-application
  name: quarkus-component-e2e
  namespace: appstudio-e2e-test
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkus-component-e2e
    weight: 100
status: {}
