apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: quarkus-component-e2e
  namespace: appstudio-e2e-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: e2e-demo-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: quarkus-component-e2e
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: quarkus-component-e2e-
      labels:
        build.appstudio.openshift.io/application: e2e-demo-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: quarkus-component-e2e
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: appstudio-e2e-test
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/psturc/test-images:74b94ec75c8f471ea34a7834c20e143f-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:05062775336d3f8efa9eb75357af8a6bd376fa57
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: quarkus-component-e2e/$(tt.params.git-revision)
    status: {}
status: {}
